sudo: required

languade: java

jdk:
  - oraclejdk8
  
services:
  - docker
  - postgresql

env:
  global:
    - DOCKER_IMAGE=roadbuddy-web-application
    - DOCKER_REPO=roadbuddy/$DOCKER_IMAGE
    - COMMIT=${TRAVIS_COMMIT::7}

before_script:
  - if [[ $TRAVIS_TAG =~ [[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$ ]]; then
      export VERSION=${BASH_REMATCH};
    else
      export VERSION=$COMMIT;
    fi
  - psql -U postgres -d postgres -c "CREATE DATABASE roadbuddy WITH OWNER;" -v ON_STOP_ERROR=1

script:
  - mvn clean package
  - docker build -t $DOCKER_REPO:$VERSION --rm .

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker save --output $DOCKER_IMAGE-$VERSION.tar.gz $DOCKER_REPO:$VERSION
  - docker tag $DOCKER_REPO:$VERSION $DOCKER_REPO:latest
  - docker push $DOCKER_REPO
  - docker logout

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: $DOCKER_IMAGE-$VERSION.tar.gz
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
