spring:
  data:
    rest:
      base-path: /api

---

spring:
  profiles: devel

db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1:5432/proddatabase
  username: roadbuddy
  password: roadbuddy

hibernate:
  dialect:
  show_sql: true
  hmb2ddl:
    auto: create
---

spring:
  profiles: prod

db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://prodhost:prodport/proddatabase
  username: produsername
  password: prodpass

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  hmb2ddl:
    auto: create
