spring:
  data:
    rest:
      base-path: /api/dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/roadbuddy
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---

spring:
  profiles: prod
  data:
    rest:
      base-path: /api/v1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://web-app-postgres:5432/roadbuddy_db
    username: roadbuddy
